version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: customer-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
